name: web3dart_async_builders
description: Extension of the web3dart package that includes the dart contract generator from abi.
version: 3.0.1
repository: https://github.com/cubealgos/web3dart_builders
homepage: https://cubealgos.xyz

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  build: ^4.0.3
  code_builder: ^4.11.0
  built_collection: ^5.1.1
  path: ^1.9.1
  dart_style: ^3.1.3
  wallet: ^0.0.17
  web3dart_async: ^3.0.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.27.0
  build_runner: ^2.5.4
  build_config: ^1.2.0
  build_test: ^3.5.4
